### ISSUE TITLE
Strange artifacts in tabline names

### ISSUE THREAD

**Issue by languitar** [gcmt/taboo.vim#22] opened 2017-11-13 12:26 UTC
From time to time I see strange artifacts in the tabline for the tab names like the following one:
![2017-11-13t13 25 07 01 00](https://user-images.githubusercontent.com/1336287/32725647-376e4c04-c876-11e7-8cdc-c175837b9a01.png)

**Comment by tsiemens** [comment] 2018-10-16 16:39
I see this deterministically when airline is also enabled (with `let g:taboo_tabline = 0`)

I can only assume that something in airline is grabbing the string, and doesn't parse out the highlights properly.

Maybe one option would be to add a new flag to turn off tabline highlighting, or to automatically disable them if `taboo_tabline` is 0

**Comment by languitar** [comment] 2018-10-16 17:43
@chrisbra do you have an idea about this issue?

**Comment by chrisbra** [comment] 2018-10-16 18:06
When does that happen?
Also in such a case, what is the output of eval'ing the result of the tabline setting? And also what vim versions?

**Comment by tsiemens** [comment] 2018-10-19 01:10
To reproduce for me, on (VIM - Vi IMproved 8.1, Included patches: 1-146)
Open vim, and create two different tabs. Don't rename the tabs.
In one of the tabs, open a file, and make some change to it, but do not save the file.
Examine the tabline on the left side. It will resemble the above shot, with `foo.txt%#TabModifiedSelected#*%#TabLineSel#` as the tab title for tab with the modified file.

If you switch tabs to focus on the other tab you have open, it will change to `foo.txt%#TabModified#*%#TabLine#`

Tabline settings (hopefully this is what you meant).
```
:let g:taboo_tabline
g:taboo_tabline       #0
```

```
:let g:taboo_tab_format
g:taboo_tab_format      %f%m
```

```
:let g:airline#extensions#tabline#enabled
g:airline#extensions#tabline#enabled #1
```

**Comment by chrisbra** [comment] 2018-10-22 09:58
I see what is going on. If you have airline enabled, the tabline setting will be set to `%!airline#extensions#tabline#get()`. This function dynamically builds the tabline string to be used by Vim and will eventually call `%{airline#extensions#tabline#title(1)}` to get the title per tabpage. [airline#extensions#tabline#title()](https://github.com/vim-airline/vim-airline/blob/08e9aa5386eecfd6a6cbde1eff240619cd81beed/autoload/airline/extensions/tabline.vim#L138-L141) basically calls `TabooTabTitle()` for the given tab page. Unfortunately, this function returns highlighting groups for modified buffers like this: `vimrc.old%#TabModifiedSelected#*%#TabLineSel#`, which I believe will be interpreted by Vim literally, since this comes from a `%{...}` expression evaluation and I believe the result is taken literally as the string to be displayed, without evaluating the highlighting groups (in contrast to what is used by e.g. a `%!` expression, where the result is evaluated again and highlighting groups will be set correctly).

So I think, this needs to be fixed by taboo, to prevent returning additional highlighting groups in the `TabooTitle()` function (perhaps by using an additional parameter, which would need an adjustment on airline as well).

**Comment by betterphp** [comment] 2018-11-30 11:57
Could [this function](https://github.com/gcmt/taboo.vim/blob/master/plugin/taboo.vim#L174) be modified to just return an empty string if `g:taboo_tabline` is 0? Basically as @chrisbra said but use `g:taboo_tabline` instead of adding a flag to the function so it can be solved without having to edit airline too.

**Comment by gcmt** [comment] 2019-07-27 12:40
Should be solved

**Closed** 2019-07-27 12:39 UTC
